# A sem-ver version requirement of trunk required for this project
trunk-version = "*"

# NOTE: after local version bump probably need some configuration https://trunkrs.dev/advanced/
[build]
#serve_base = "/wordle-helper/"
dist = "../dist"
[serve]
# The address to serve on.
address = "127.0.0.1"
# The port to serve on.
port = 4242
# Open a browser tab once the initial build is complete.
open = false
