attr_value_brace_style = "WhenRequired"         # "Always", "AlwaysUnlessLit", "WhenRequired" or "Preserve"
indentation_style      = "Auto"                 # "Tabs", "Spaces" or "Auto"
macro_names            = ["leptos::view, view"] # Macro names which will be formatted
max_width              = 100                    # Maximum width of each line
newline_style          = "Auto"                 # "Unix", "Windows" or "Auto"
tab_spaces             = 4                      # Number of spaces per tab
