edition = "2021"

group_imports       = "StdExternalCrate"
imports_granularity = "Crate"

comment_width               = 100
format_code_in_doc_comments = true
format_strings              = true
max_width                   = 80
use_field_init_shorthand    = true
use_small_heuristics        = "Max"
wrap_comments               = true
