[package]
name = "wordlists"
authors.workspace = true
description.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]

[lints]
workspace = true
